"use strict";
const test=require('node:test'), assert=require('node:assert/strict');
const {server}=require('../server');
const {createRequest, CONTRACT_VERSION}=require('../contracts/investment-contract');
const marketBrief=require('../data/market-brief-2026-10-08.json');
const marketBriefNext=require('../data/market-brief-2026-10-09.json');
test('HTTP flows: pages, independent cookies, review gating, import failure and disabled execution',async t=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(()=>new Promise(resolve=>{server.closeAllConnections();server.close(resolve);}));
  const base='http://127.0.0.1:'+server.address().port;
  for(const page of ['/','/catalog','/investment','/investment-v0.10','/merchant','/risk-workbench','/versions/merchant.js','/versions/investment-legacy.js','/versions/risk-workbench.js','/contracts/investment-agent.v1.schema.json','/contracts/examples/health-check.request.json','/contracts/examples/health-check.response.json','/data/market-brief-2026-10-08.json','/data/market-brief-2026-10-09.json']) assert.equal((await fetch(base+page)).status,200);
  assert.match(await fetch(base+'/').then(r=>r.text()),/个人投资顾问/);
  assert.match(await fetch(base+'/catalog').then(r=>r.text()),/店主财务助手/);
  assert.match(await fetch(base+'/investment').then(r=>r.text()),/现在先检查什么/);
  assert.match(await fetch(base+'/investment-v0.10').then(r=>r.text()),/旧版/);
  assert.equal((await fetch(base+'/contracts/investment-agent.v1.schema.json').then(r=>r.json())).$id,'https://fintechathon-agent.github.io/contracts/investment-agent.v1.schema.json');
  await t.test('all page assets load with the right type including the separate product stylesheet',async()=>{
    const assets=new Set(['/versions/presentation.mjs']);
    for(const route of ['/','/catalog','/investment','/investment-v0.10','/merchant']){
      const html=await fetch(base+route).then(r=>r.text());
      assert.match(html,/product-overrides\.css/);
      for(const match of html.matchAll(/(?:src|href)="(\/versions\/[^"]+)"/g))assets.add(match[1]);
    }
    for(const asset of assets){
      const response=await fetch(base+asset);
      assert.equal(response.status,200,asset);
      assert.match(response.headers.get('content-type'),asset.endsWith('.css')?/text\/css/:/javascript/);
      const body=await response.text();
      assert.ok(body.length>0,asset);
      if(asset.endsWith('.css'))assert.doesNotMatch(body,/^\+/m);
      if(asset.endsWith('product-overrides.css'))assert.match(body,/--product-shell:ready/);
    }
  });
  assert.equal((await fetch(base+'/data/demo-portfolio.json')).status,404);
  assert.equal((await fetch(base+'/server.js')).status,404);
  const a=await fetch(base+'/api/merchant/ledger'), cookie=a.headers.get('set-cookie').split(';')[0], data=await a.json();
  const headers={Cookie:cookie,'Content-Type':'application/json'};
  assert.equal((await fetch(base+'/api/merchant/insights',{headers})).status,422);
  assert.equal((await fetch(base+'/api/merchant/export?type=review',{headers})).status,422);
  await fetch(base+'/api/merchant/bill?id='+encodeURIComponent('外卖平台:MT-001'),{headers});
  assert.equal((await fetch(base+'/api/merchant/review',{method:'POST',headers,body:JSON.stringify({revision:data.revision,confirmed:true})})).status,200);
  assert.equal((await fetch(base+'/api/merchant/insights',{headers})).status,200);
  const scenario=await fetch(base+'/api/merchant/scenario?bill='+encodeURIComponent('微信:WX-002')+'&delay=3',{headers});
  assert.equal(scenario.status,200);assert.equal((await scenario.json()).moved_to,'2026-10-08');
  const notice=await fetch(base+'/api/merchant/notice',{method:'POST',headers,body:JSON.stringify({id:'overdue',status:'verified',note:'已联系平台，等回款'})});
  assert.equal(notice.status,200);
  const notices=await fetch(base+'/api/merchant/insights',{headers}).then(r=>r.json());
  assert.equal(notices.notices.find(n=>n.id==='overdue').status,'verified');
  assert.equal(notices.notices.find(n=>n.id==='overdue').note,'已联系平台，等回款');
  const exported=await fetch(base+'/api/merchant/export?type=review&delay=3',{headers});
  assert.match(exported.headers.get('content-disposition'),/attachment/);
  assert.equal((await exported.json()).forecast.first_gap.date,'2026-10-06');
  assert.equal((await fetch(base+'/api/merchant/insights')).status,422);
  assert.equal((await fetch(base+'/api/merchant/import',{method:'POST',headers,body:'{"currency":"USD"}'})).status,422);
  assert.equal((await fetch(base+'/api/merchant/ledger',{headers}).then(r=>r.json())).reviewed,true);
  assert.equal((await fetch(base+'/api/paper-trade/execute',{method:'POST',headers,body:'{"approval":{"status":"APPROVED","token":"client-forged"}}'})).status,503);
  assert.equal((await fetch(base+'/api/merchant/reset',{method:'POST',headers:{...headers,Origin:'https://example.com'},body:'{}'})).status,403);
  const request=createRequest({requestId:'req-http-test-001',riskProfile:{investment_horizon_days:365,max_drawdown:.1,liquidity_need:'medium'}});
  const taskResponse=await fetch(base+'/api/health-check/run',{method:'POST',headers,body:JSON.stringify(request)});
  assert.equal(taskResponse.status,200);
  const task=await taskResponse.json();
  assert.equal(task.contract_version,CONTRACT_VERSION);
  assert.equal(task.request_id,request.request_id);
  assert.equal(task.risk_handoff.execution_allowed,false);
  assert.equal(task.trace.task_id,task.task_state.task_id);
  assert.ok(task.audit_evidence.events.some(event=>event.event_type==='contract.accepted'));
  assert.equal(task.task_state.status,'HANDOFF_REQUIRED');assert.equal(Object.keys(task.tool_results).length,4);
  const contextualRequest=createRequest({requestId:'req-http-market-context-001',riskProfile:request.input.risk_profile,marketContext:marketBrief});
  const contextualResponse=await fetch(base+'/api/health-check/run',{method:'POST',headers,body:JSON.stringify(contextualRequest)});
  assert.equal(contextualResponse.status,200);
  const contextual=await contextualResponse.json();
  assert.equal(contextual.artifacts.market_context.brief_id,marketBrief.brief_id);
  assert.equal(contextual.artifacts.market_context.unresolved_conflicts[0].signal_id,'oil-message-conflict');
  assert.equal(contextual.risk_handoff.evidence.market_context_id,contextual.artifacts.market_context.context_id);
  assert.equal(contextual.risk_handoff.execution_allowed,false);
  assert.ok(Object.values(contextual.tool_results).some(result=>result.tool_name==='market-brief.context'));
  const nextRequest=createRequest({requestId:'req-http-market-20261009-001',riskProfile:request.input.risk_profile,marketContext:marketBriefNext});
  const nextResponse=await fetch(base+'/api/health-check/run',{method:'POST',headers,body:JSON.stringify(nextRequest)});
  assert.equal(nextResponse.status,200);
  const next=await nextResponse.json();
  assert.equal(next.artifacts.market_context.brief_id,marketBriefNext.brief_id);
  assert.deepEqual(next.artifacts.market_context.unresolved_conflicts.map(signal=>signal.signal_id),['rates-view-data-conflict']);
  assert.equal(next.risk_handoff.evidence.audit_id,next.audit_evidence.audit_id);
  assert.equal(next.risk_handoff.execution_allowed,false);
  const bridgeResponse=await fetch(base+'/api/risk-workbench/handoff',{method:'POST',headers,body:JSON.stringify({request:nextRequest})});
  assert.equal(bridgeResponse.status,200);
  const bridge=await bridgeResponse.json();
  assert.equal(bridge.risk_workbench.integration_mode,'READ_ONLY_HANDOFF_PREVIEW');
  assert.equal(bridge.risk_workbench.source.request_id,nextRequest.request_id);
  assert.equal(bridge.risk_workbench.evidence.audit_id,bridge.agent_response.audit_evidence.audit_id);
  assert.equal(bridge.risk_workbench.decision.execution_allowed,false);
  assert.equal((await fetch(base+'/api/audit/'+task.task_state.task_id)).status,200);
  const investmentFile=await fetch(base+'/api/task/'+task.task_state.task_id+'/export');
  assert.match(investmentFile.headers.get('content-disposition'),/attachment/);
  assert.equal((await investmentFile.json()).task_state.task_id,task.task_state.task_id);
  const legacyResponse=await fetch(base+'/api/health-check/run',{method:'POST',headers,body:JSON.stringify({risk_profile:request.input.risk_profile,portfolio:request.input.portfolio})});
  assert.equal(legacyResponse.status,422);
  assert.equal((await legacyResponse.json()).error.code,'INVALID_CONTRACT');
  const invalidContract={...request};delete invalidContract.contract_version;
  const invalidResponse=await fetch(base+'/api/health-check/run',{method:'POST',headers,body:JSON.stringify(invalidContract)});
  assert.equal(invalidResponse.status,422);
  const invalidBody=await invalidResponse.json();
  assert.equal(invalidBody.contract_version,CONTRACT_VERSION);
  assert.equal(invalidBody.request_id,request.request_id);
  assert.equal(invalidBody.error.retryable,false);
  assert.equal(invalidBody.error.stage,'BACKEND');
  assert.ok(invalidBody.error.recovery);
});
